In [1]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9,10]
type(lista)

list

In [ ]:
np_arr = np.array(lista)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
matrica = [ {1,2,3}, {4,5,6}, {7,8,9}]
np_matrix = np.array(matrica)


array([{1, 2, 3}, {4, 5, 6}, {8, 9, 7}], dtype=object)

In [ ]:
# zemanje podatoci od 10 array
print(np_arr)
print(np_arr[2])
print(np_arr[2:5])

[ 1  2  3  4  5  6  7  8  9 10]
3
[3 4 5]


In [20]:
print(np_matrix)
print(np_matrix[0][0])

[{1, 2, 3} {4, 5, 6} {8, 9, 7}]


TypeError: 'set' object is not subscriptable

In [32]:
np_random_arr = np.random.randint(5, 500, size= 50)
np_random_arr

array([113, 305, 132, 463, 216, 284, 213, 395, 470, 314, 476, 493,  53,
       224, 289,  78, 117, 336,  67,  66,  23, 308, 484, 216, 443, 190,
       478, 149, 306, 211, 212, 294, 127, 101,  70, 109, 170, 259, 423,
        40, 298,  90, 463, 426, 463, 256,  14, 294, 107, 273])

In [38]:
filter_arr = np_random_arr %2 ==0
np_random_arr[filter_arr]


array([132, 216, 284, 470, 314, 476, 224,  78, 336,  66, 308, 484, 216,
       190, 478, 306, 212, 294,  70, 170,  40, 298,  90, 426, 256,  14,
       294])

In [42]:
print(np_random_arr.sum())
print(np_random_arr.max())
print(np_random_arr.min())
print(np_random_arr.mean())

12401
493
14
248.02


In [43]:
import numpy as np
niza_broevi = np.random.randint (50,100, size = 10)
parni = niza_broevi[niza_broevi % 2 == 0]
print(f"Parni broevi se: {parni}")
nad_70 = niza_broevi[niza_broevi > 70]
print(f"broevi nad 70 se {nad_70}")
najgolem_broj = np.max(niza_broevi)
najmal_broj = np.min(niza_broevi)
print(f"Najgolem broj e {najgolem_broj}")
print(f"Najmal broj e {najgolem_broj}")

Parni broevi se: [90 66 86 76 50]
broevi nad 70 se [73 90 77 86 73 76 99]
Najgolem broj e 99
Najmal broj e 99


In [2]:
rand_arr1 = np.random.randint(1, 100, size=10)
rand_arr2 = np.random.randint(1, 100, size=10)
print (rand_arr1)
print (rand_arr2)

[20 31 24 81 61 37 94  7 82 81]
[54 56  2  1 34 49 70 87 79 43]


In [8]:
result_sum = np.add(rand_arr1, rand_arr2)
result_substract = np.subtract(rand_arr2, rand_arr1)
result_multiply = np.multiply(rand_arr2, rand_arr1)
result_divide = np.divide(rand_arr1, rand_arr2)

print(result_divide)

[3.70370370e-01 5.53571429e-01 1.20000000e+01 8.10000000e+01
 1.79411765e+00 7.55102041e-01 1.34285714e+00 8.04597701e-02
 1.03797468e+00 1.88372093e+00]
